# Generated by Django 3.2.5 on 2021-07-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('district', models.CharField(max_length=64)),
                ('divison', models.CharField(max_length=64)),
                ('upazilla', models.CharField(max_length=64)),
                ('adress', models.CharField(max_length=128)),
                ('profession', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=14, unique=True)),
                ('password', models.CharField(max_length=24)),
                ('verified', models.BooleanField(default=False)),
                ('user_role', models.CharField(default='Customer', max_length=64)),
            ],
        ),
    ]
