# Generated by Django 3.2.4 on 2021-07-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210713_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
